server:
  port: 8090
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: localhost
      ms-client: localhost
      ms-credits: localhost
      ms-movement: localhost
      ms-loan: localhost
      ms-debit-card: localhost
spring:
  application:
    name: service-mobile-wallet
  data:
    mongodb:
      uri: mongodb://localhost:27017/MobileWalletDB
      auto-index-creation: true
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      bankaccountCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde git