server:
  port: 8081
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: ms-bank-account
      ms-client: ms-client
      ms-credits: ms-credits
      ms-movement: ms-movement
      ms-debit-card: ms-debit-card
spring:
  application:
    name: service-loan
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: LoanDB
      auto-index-creation: true
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      loan:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde git